project:
  type: website

website:
  title: "IS415-GAA-2024"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    left: 
      - text: "Hands-on Exercises"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"

      - text: "In-class Exercises"
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "In-class Exercise 3B"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03_NKDE.html"
      - text: "Take Home Exercises"
        menu: 
          - text: "Take Home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

