project:
  type: website

website:
  title: "IS415-GAA-2024"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    left: 
      - text: "Hands-on Exercises"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Exercise 3B"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_NKDE.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 9"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
          - text: "Hands-on Exercise 10"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
          - text: "Hands-on Exercise 11"
            href: "Hands-on_Ex/Hands-on_Ex11/Hands-on_Ex11.html"

      - text: "In-class Exercises"
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "In-class Exercise 5"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
          - text: "In-class Exercise 9"
            href: "In-class_Ex/In-class_Ex09/In-class_Ex09.html"
          - text: "In-class Exercise 10"
            href: "In-class_Ex/In-class_Ex10/In-class_Ex10.html"
          - text: "In-class Exercise 11"
            href: "In-class_Ex/In-class_Ex11/In-class_Ex11.html"


      - text: "Take Home Exercises"
        menu: 
          - text: "Take Home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take Home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02a.html"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

